### PR TITLE
Clarify Mapping & Param naming

### PR DESCRIPTION
**Pull request by alexroan**
Changes:
* Named mapping parameters
* Intuitive naming for the mappings themselves

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
Thanks!

For this course, we have chosen to be extra explicit with mapping names, a mapping of token addresses to balances would be named

```javascript
mapping(uint256 => uint256) s_tokenAddressToBalance;
```

Personally, I prefer this naming convention as it is clear to me the types the mapping is looking for. Names like `s_priceFeed`  obfuscate what the key of the mapping is. Just a different style preference. 

I have added your dev comments in 336e44f. Thank you!

**Comment by alexroan** [comment]
Reopening this as I think it's relevant.

The information in the long name `s_tokenAddressToBalance` is able to be defined in the parameter names, a feature that was implemented to prevent the need for long explicit mapping names and comments:

```
mapping(address tokenAddress => uint256 balance) s_balances;
```
is far easier to reason about than:
```
mapping(address => uint256) s_tokenAddressToBalance;
```

Since the codebase is using 0.8.19, we should probably teach the latest and greatest in that version, no?

**Comment by alexroan** [comment]
It's event more helpful when you get to nested mappings:

```solidity
mapping(address => mapping(address => uint256)) private s_userToTokenAddressToAmountDeposited;
```
becomes:
```solidity
mapping(address user => mapping(address collateralToken => uint256 amount)) private s_collateralDeposited;
```

Let's look at how it's read in a function:

```solidity
function fooBar(address user, address token) public {
    ...
    uint256 deposited = s_userToTokenAddressToAmountDeposited[user][token]; // yuck
    ...
}
```
becomes:
```solidity
function fooBar(address user, address token) public {
    ...
    uint256 deposited = s_collateralDeposited[user][token]; // yay
    ...
}
```

The name is now what the value actually represents: the collateral deposited.

* Succinct
* Intuitively descriptive
* Easy to understand the key=>value pairs because they're named in the definition.

**Comment by PatrickAlphaC** [comment]
When you're reading the code, I don't think it's helpful to have to look up at the variable declaration to know what the types of mapping are.

However, this isn't a hill I'll die on, and I respect and admire your opinion, so I will merge.

**Pull request merged**
